services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - POCKETBASE_URL
    ports:
      - "${PORT:?}:3000"
    env_file:
      - .env
    restart: unless-stopped
